Fix edit expired bug
AY2021S2-CS2103T-W14-4/tp pull request #179
Opened 2021-04-09 13:02 UTC by hengyongming

2021-04-09 13:09 UTC, khiaxeng approved these changes
LGTM

2021-04-09 13:53 UTC, CSmortal commented on src/main/java/seedu/taskify/logic/commands/EditCommand.java
> +
I think `.getStatus().toString()` is a violation of Law of Demeter

2021-04-10 03:59 UTC, noelmathewisaac approved these changes

2021-04-10 03:59 UTC, merged

2021-04-10 04:02 UTC, CSmortal requested changes
I think for EditCommand line 87, you could just use `taskToEdit.getStatus().equals(new Status(StatusType.EXPIRED))`

2021-04-10 04:02 UTC, CSmortal commented on src/main/java/seedu/taskify/logic/commands/EditCommand.java
> +
It might not since all objects have `toString`, but since `Status` has an overriden `toString`, it might be a violation. Not 100% sure